#!/bin/sh
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Developer Local Compile Process
# ===========================================================================================
# 1. Clean up the target folder
# 2. Generate the Build Number (from git commit count) and Build Date
# 3. Build the Service
# 4. Copy the jar file to the Lib Folder
# 5. Start the Service using ./run script and then test it with ./test script
#
# After the Successful build and Startup of the Service, It should show the Build No. & Date
# -------------------------------------------------------------------------------------------
SERVICE=`getServiceName`
CONTAINER=`getServiceName 4`

echo "---------------------------------------------------------------------------------------"
echo "Compiling $SERVICE Microservice"
echo "---------------------------------------------------------------------------------------"
echo "Clean up the target folder: mvn clean"
echo "---------------------------------------------------------------------------------------"
mvn clean
# -------------------------------------------------------------------------------------------
echo "Git Commit Count = "`git rev-list HEAD --count`
echo "---------------------------------------------------------------------------------------"
generateBuildNumber $SERVICE
# -------------------------------------------------------------------------------------------
echo "Build the $SERVICE Microservice : mvn -e package"
echo "---------------------------------------------------------------------------------------"
mvn -e package
# -------------------------------------------------------------------------------------------
#echo cp target/*service*.?ar lib/
echo "---------------------------------------------------------------------------------------"
cp target/*service*-spring-boot.jar src/docker/$CONTAINER-spring-boot.jar
cp target/*service*?.?.?.jar src/docker/$CONTAINER-thin.jar
cp target/libs/* src/docker/libs/
echo "Copy the Property File to the Docker Directory (src/docker)"
cp src/main/resources/application.properties src/docker/
cp src/main/resources/application.properties .
echo "---------------------------------------------------------------------------------------"
# -------------------------------------------------------------------------------------------
# - Build Docker Images (this can be done thru maven also)
# -------------------------------------------------------------------------------------------
echo "$SERVICE Microservice Build Process Complete .............. "
echo "---------------------------------------------------------------------------------------"
echo "Start the Service using ./run script and then test it with ./test script"
echo "After the Successful build and Startup of the Service, It should show the Build No. & Date"
echo "---------------------------------------------------------------------------------------"
