#!/bin/sh

PORT=9090
API_VERSION=v1
SERVICE=payment

echo "---------------------------------------------------------------------------------------"
echo "Testing $SERVICE Microservice"
echo "---------------------------------------------------------------------------------------"
echo "---------------------------------------------------------------------------------------"
echo "curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/home"
curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/home
echo ""
echo "---------------------------------------------------------------------------------------"
echo "curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/health"
curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/health
echo ""
echo "---------------------------------------------------------------------------------------"
echo "curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/ready"
curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/ready
echo ""
echo "---------------------------------------------------------------------------------------"
echo "curl -X POST localhost:$PORT/api/$API_VERSION/$SERVICE/service/restart"
curl  -X POST localhost:$PORT/api/$API_VERSION/$SERVICE/service/restart
echo ""
echo "---------------------------------------------------------------------------------------"
sleep 3
echo "curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/home"
curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/home
echo ""
echo "---------------------------------------------------------------------------------------"
echo "curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/ready"
curl localhost:$PORT/api/$API_VERSION/$SERVICE/service/ready
echo ""
echo "---------------------------------------------------------------------------------------"
