#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Build Container
# -------------------------------------------------------------------------------------------
ORG=`../../getServiceName 2`
SERVICE=`../../getServiceName`
echo "docker build --force-rm -f Dockerfile -t $ORG/$SERVICE . "
docker build --force-rm -f Dockerfile -t $ORG/$SERVICE . 
