#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Scan Container for Vulnerabilities
# -------------------------------------------------------------------------------------------
ORG=`../../getServiceName 2`
SERVICE=`../../getServiceName`
echo "Scanning $SERVICE for vulnerabilities"
docker scan $ORG/$SERVICE
