#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Shell Container
# -------------------------------------------------------------------------------------------
SERVICE=`../../getServiceName`
echo "docker container exec -it $SERVICE bash"
docker container exec -it $SERVICE bash
