#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Start Container
# -------------------------------------------------------------------------------------------
ORG=`../../getServiceName 2`
SERVICE=`../../getServiceName`
echo "docker container run --name $SERVICE -d --rm -p 9010:9090 $ORG/$SERVICE"
docker container run --name $SERVICE -d --rm -p 9010:9090 $ORG/$SERVICE
echo "Container id for $SERVICE ="`docker container ls | grep $SERVICE | tr -s " " | cut -d " " -f 1`
docker container ls | grep $SERVICE | tr -s " " | cut -d " " -f 1 > $SERVICE.cid
