#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Stop Container
# -------------------------------------------------------------------------------------------
ORG=`../../getServiceName 1`
SERVICE=`../../getServiceName 4`
echo "docker container stop $SERVICE"
docker container stop $SERVICE
mv $SERVICE.cid $SERVICE.cid.old
