#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Stop Container
# -------------------------------------------------------------------------------------------
ORG=`../../getServiceName 2`
SERVICE=`../../getServiceName`
echo "docker container stop $SERVICE"
docker container stop $SERVICE
mv $SERVICE.cid $SERVICE.cid.old
